app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateTimeField, SelectField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields.html5 import DateField
from wtforms_components import TimeField


from ..models import Events, Rso, University


class EventForm(FlaskForm):
    """
    Form for admin to add or edit a university
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    date = DateField('Date', validators=[DataRequired()], format='%Y-%m-%d')
    time = TimeField('Time(H:M)', validators=[DataRequired()], format='%H:%M')
    location = StringField('Location', validators=[DataRequired()])
    event_type = SelectField(u'Type', choices=[('Public', 'Public'), ('Private', 'Private'), ('RSO', 'RSO') ])
    university = QuerySelectField(query_factory=lambda: University.query.all(),
                                  get_label="name")
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    """
    Form for admin to add or edit a university
    """
    comment = StringField('Comment', validators=[DataRequired()])
    rating = StringField('Rating', validators=[DataRequired()])
    #date = DateField('Date', validators=[DataRequired()], format='%Y-%m-%d')
    #time = DateTimeField('Time(H:M)', validators=[DataRequired()], format='%H:%M')
    #location = StringField('Location', validators=[DataRequired()])
    submit = SubmitField('Submit')

class RsoForm(FlaskForm):
    """
    Form for admin to add or edit a university
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    university = QuerySelectField(query_factory=lambda: University.query.all(),
                                  get_label="name")
    submit = SubmitField('Submit')


class StudentAssignForm(FlaskForm):
    """
    Form for admin to assign universities and roles to students
    """
    university = QuerySelectField(query_factory=lambda: University.query.all(),
                                  get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label="name")
    submit = SubmitField('Submit')

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import home
from ..models import Events, Comments, University, Rso
from .forms import EventForm, CommentForm, RsoForm
from .. import db


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    print("hi")


    return render_template('home/dashboard.html', title="Dashboard")

# add admin dashboard view
@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")


@home.route('/events', methods=['GET', 'POST'])
@login_required
def list_events():
    """
    List all events
    """

    print("hi")

    events = Events.query.all()

    return render_template('home/events/events.html',
                           events=events, title="Events")

@home.route('/events/add', methods=['GET', 'POST'])
@login_required
def add_event():
    """
    Add a event to the database
    """

    add_event = True

    form = EventForm()
    if form.validate_on_submit():
        event = Events(name=form.name.data,
                                description=form.description.data, date=form.date.data, time=form.time.data, location=form.location.data, event_type=form.event_type.data)
        event.univeristy = form.university.data

        try:
            # add university to the database
            db.session.add(event)
            db.session.commit()
            flash('You have successfully added a new event.')
        except:
            # in case university name already exists
            flash('Error: event name already exists.')

        # redirect to universities page
        return redirect(url_for('home.list_events'))

    # load university template
    return render_template('home/events/event.html', action="Add",
                           add_event=add_event, form=form,
                           title="Add Event")

@home.route('/events/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_event(id):
    """
    Edit a university
    """

    add_event = False

    event = Events.query.get_or_404(id)
    form = EventForm(obj=event)
    if form.validate_on_submit():
        event.name = form.name.data
        event.description = form.description.data
        db.session.commit()
        flash('You have successfully edited the event.')

        # redirect to the universities page
        return redirect(url_for('home.list_events'))

    form.description.data = event.description
    form.name.data = event.name
    return render_template('home/events/event.html', action="Edit",
                           add_event=add_event, form=form,
                           even=event, title="Edit Event")


@home.route('/events/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_event(id):
    """
    Delete a university from the database
    """

    event = Events.query.get_or_404(id)
    db.session.delete(event)
    db.session.commit()
    flash('You have successfully deleted the event.')

    # redirect to the universities page
    return redirect(url_for('home.list_events'))

    return render_template(title="Delete Event")

@home.route('/events/<int:id>/comments/', methods=['GET', 'POST'])
@login_required
def event_comments(id):
    """
    Delete a university from the database
    """

    comments = Comments.query.filter(Comments.event_id==id)

    # redirect to the universities page

    return render_template('home/events/comments.html',
                           comments=comments, event_id=id, title="Comments")

@home.route('/events/<int:eventid>/comments/add', methods=['GET', 'POST'])
@login_required
def add_comment(eventid):
    """
    Add a event to the database
    """

    add_comment = True

    form = CommentForm()
    if form.validate_on_submit():
        comment = Comments(comment=form.comment.data,
                                rating=form.rating.data, event_id=eventid)

        try:
            # add university to the database
            db.session.add(comment)
            db.session.commit()
            flash('You have successfully added a new comment.')
        except:
            # in case university name already exists
            flash('Error: comment name already exists.')

        # redirect to universities page
        return redirect(url_for('home.event_comments', id=eventid))

    # load university template
    return render_template('home/events/comment.html', action="Add",
                           add_comment=add_comment, form=form,
                           title="Add Comment")

@home.route('/events/<int:eventid>/comments/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_comment(id, eventid):
    """
    Edit a university
    """

    add_comment = False

    comment = Comments.query.get_or_404(id)
    form = CommentForm(obj=comment)
    if form.validate_on_submit():
        comment.comment = form.comment.data
        comment.rating = form.rating.data
        db.session.commit()
        flash('You have successfully edited the comment.')

        # redirect to the universities page
        return redirect(url_for('home.event_comments', id=eventid))

    form.rating.data = comment.rating
    form.comment.data = comment.comment
    return render_template('home/events/comment.html', action="Edit",
                           add_comment=add_comment, form=form,
                           comment=comment, title="Edit Comment")

@home.route('/events/<int:eventid>/comments/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_comment(id, eventid):
    """
    Delete a university from the database
    """

    comment = Comments.query.get_or_404(id)
    db.session.delete(comment)
    db.session.commit()
    flash('You have successfully deleted the comment.')

    # redirect to the universities page
    return redirect(url_for('home.event_comments', id=eventid))

    return render_template(title="Delete Comment")


@home.route('/rsos', methods=['GET', 'POST'])
@login_required
def list_rsos():
    """
    List all rsos
    """

    print("hi")

    rsos = Rso.query.all()

    return render_template('home/rsos/rsos.html',
                           rsos=rsos, title="Rsos")

@home.route('/rsos/add', methods=['GET', 'POST'])
@login_required
def add_rso():
    """
    Add a rso to the database
    """

    add_rso = True

    form = RsoForm()
    if form.validate_on_submit():
        uname = form.university.data
        uid = db.select([University.id]).where(University.name.in_([str(uname)]))
        rso = Rso(name=form.name.data,
                                description=form.description.data,university_id=uid)
        try:
            # add university to the database
            db.session.add(rso)
            db.session.commit()
            flash('You have successfully added a new rso.')
        except ValueError as e:
            print(e)
            # in case university name already exists
            flash('Error: rso name already exists.')

        # redirect to universities page
        return redirect(url_for('home.list_rsos'))

    # load university template
    return render_template('home/rsos/rso.html', action="Add",
                           add_rso=add_rso, form=form,
                           title="Add Rso")

@home.route('/rsos/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_rso(id):
    """
    Edit a university
    """

    add_rso = False

    rso = Rso.query.get_or_404(id)
    form = RsoForm(obj=rso)
    if form.validate_on_submit():
        rso.name = form.name.data
        rso.description = form.description.data
        db.session.commit()
        flash('You have successfully edited the rso.')

        # redirect to the universities page
        return redirect(url_for('home.list_rsos'))

    form.description.data = rso.description
    form.name.data = rso.name
    return render_template('home/rsos/rso.html', action="Edit",
                           add_rso=add_rso, form=form,
                           even=rso, title="Edit Rso")
                                                   
@home.route('/rsos/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_rso(id):
    """
    Delete a university from the database
    """

    rso = Rso.query.get_or_404(id)
    db.session.delete(rso)
    db.session.commit()
    flash('You have successfully deleted the rso.')

    # redirect to the universities page
    return redirect(url_for('home.list_rsos'))

    return render_template(title="Delete Rso")

app/templates/home/events/comment.html
{% import "bootstrap/wtf.html" as wtf %} {% extends "base.html" %} {% block
title %} {% if add_comment %} Add Comment {% else %} Edit Comment {% endif %} {%
endblock %} {% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
          {% if add_comment %}
          <h1>Add Comment</h1>
          {% else %}
          <h1>Edit Comment</h1>
          {% endif %}
          <br />
          {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/events/comments.html
{% import "bootstrap/utils.html" as utils %} {% extends "base.html" %} {% block
title %}Comments{% endblock %} {% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br />
        {{ utils.flashed_messages() }}
        <br />
        <h1 style="text-align:center;">Comments</h1>
        {% if comments %}
        <hr class="intro-divider" />
        <div class="center">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th width="50%">Comment</th>
                <th width="15%">Rating</th>
                <th width="15%">Edit</th>
                <th width="15%">Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for comment in comments %}
              <tr>
                <td>{{ comment.comment }}</td>
                <td>{{ comment.rating }}</td>
                <td>
                  <a
                    href="{{ url_for('home.edit_comment', id=comment.id, eventid=comment.event_id) }}"
                  >
                    <i class="fa fa-pencil"></i> Edit
                  </a>
                </td>
                <td>
                  <a
                    href="{{ url_for('home.delete_comment', id=comment.id, eventid=comment.event_id) }}"
                  >
                    <i class="fa fa-trash"></i> Delete
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div style="text-align: center">
          {% else %}
          <div style="text-align: center">
            <h3>No Comments have been added.</h3>
            <hr class="intro-divider" />
            {% endif %}
            <a
              href="{{ url_for('home.add_comment', eventid=event_id) }}"
              class="btn btn-default btn-lg"
            >
              <i class="fa fa-plus"></i>
              Add Comments
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

app/templates/home/events/event.html
{% import "bootstrap/wtf.html" as wtf %} {% extends "base.html" %} {% block
title %} {% if add_event %} Add Event {% else %} Edit Event {% endif %} {%
endblock %} {% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
          {% if add_event %}
          <h1>Add Event</h1>
          {% else %}
          <h1>Edit Event</h1>
          {% endif %}
          <br />
          {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/events/events.html
{% import "bootstrap/utils.html" as utils %} {% extends "base.html" %} {% block
title %}Events{% endblock %} {% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br />
        {{ utils.flashed_messages() }}
        <br />
        <h1 style="text-align:center;">Events</h1>
        {% if events %}
        <hr class="intro-divider" />
        <div class="center">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th width="15%">Name</th>
                <th width="40%">Description</th>
                <th width="15%">Date</th>
                <th width="15%">Time</th>
                <th width="15%">Location</th>
                <th width="15%">Student Count</th>
                {% if current_user.is_admin %}
                <th width="15%">Edit</th>
                <th width="15%">Delete</th>
                {% endif %}
                <th width="15%">Comments</th>
              </tr>
            </thead>
            <tbody>
              {% for event in events %} {% if event.event_type == "Public" or
              current_user.is_admin %}
              <tr>
                <td>{{ event.name }}</td>
                <td>{{ event.description }}</td>
                <td>{{ event.date }}</td>
                <td>{{ event.time }}</td>
                <td>{{ event.location }}</td>
                <td>
                  {% if event.students %} {{ event.students.count() }} {% else
                  %} 0 {% endif %}
                </td>
                {% if current_user.is_admin %}
                <td>
                  <a href="{{ url_for('home.edit_event', id=event.id) }}">
                    <i class="fa fa-pencil"></i> Edit
                  </a>
                </td>
                <td>
                  <a href="{{ url_for('home.delete_event', id=event.id) }}">
                    <i class="fa fa-trash"></i> Delete
                  </a>
                </td>
                {% endif %}
                <td>
                  <a href="{{ url_for('home.event_comments', id=event.id) }}">
                    <i class="fa fa-comment"></i> Comments
                  </a>
                </td>
              </tr>
              {% endif %} {% endfor %}
            </tbody>
          </table>
        </div>
        <div style="text-align: center">
          {% else %}
          <div style="text-align: center">
            <h3>No Events have been added.</h3>
            <hr class="intro-divider" />
            {% endif %} {% if current_user.is_authenticated %} {% if
            current_user.is_admin %}
            <a
              href="{{ url_for('home.add_event') }}"
              class="btn btn-default btn-lg"
            >
              <i class="fa fa-plus"></i>
              Add Events
            </a>
            {% endif %} {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>